### PR TITLE
Initial commit of localisation

### LINKED ISSUE #72: Localise all strings within LibZipSharp.
We should localise all the exceptions and error messages in the LibZipSharp.dll
Here is a list of all the current places a string is being used.

LibZip Text

https://github.com/xamarin/LibZipSharp/blob/master/PlatformServices.cs#L94
https://github.com/xamarin/LibZipSharp/blob/master/PlatformServices.cs#L111
https://github.com/xamarin/LibZipSharp/blob/master/PlatformServices.cs#L121
https://github.com/xamarin/LibZipSharp/blob/master/PlatformServices.cs#L152

https://github.com/xamarin/LibZipSharp/blob/master/UnixPlatformServices.cs#L66
https://github.com/xamarin/LibZipSharp/blob/master/UnixPlatformServices.cs#L169
https://github.com/xamarin/LibZipSharp/blob/master/UnixPlatformServices.cs#L325
https://github.com/xamarin/LibZipSharp/blob/master/UnixPlatformServices.cs#L350
https://github.com/xamarin/LibZipSharp/blob/master/UnixPlatformServices.cs#L355
https://github.com/xamarin/LibZipSharp/blob/master/UnixPlatformServices.cs#L363
https://github.com/xamarin/LibZipSharp/blob/master/UnixPlatformServices.cs#L374
https://github.com/xamarin/LibZipSharp/blob/master/UnixPlatformServices.cs#L385
https://github.com/xamarin/LibZipSharp/blob/master/UnixPlatformServices.cs#L387
https://github.com/xamarin/LibZipSharp/blob/master/UnixPlatformServices.cs#L416

https://github.com/xamarin/LibZipSharp/blob/master/UnixZipArchive.cs#L38

https://github.com/xamarin/LibZipSharp/blob/master/Utilities.Unix.cs#L62
https://github.com/xamarin/LibZipSharp/blob/master/Utilities.Unix.cs#L72
https://github.com/xamarin/LibZipSharp/blob/master/Utilities.Unix.cs#L144
https://github.com/xamarin/LibZipSharp/blob/master/Utilities.Unix.cs#L159

https://github.com/xamarin/LibZipSharp/blob/master/WindowsPlatformServices.cs#L64
https://github.com/xamarin/LibZipSharp/blob/master/WindowsPlatformServices.cs#L197
https://github.com/xamarin/LibZipSharp/blob/master/WindowsPlatformServices.cs#L213

https://github.com/xamarin/LibZipSharp/blob/master/WindowsZipArchive.cs#L37

https://github.com/xamarin/LibZipSharp/blob/master/ZipArchive.Unix.cs#L36
https://github.com/xamarin/LibZipSharp/blob/master/ZipArchive.Unix.cs#L46

https://github.com/xamarin/LibZipSharp/blob/master/ZipArchive.cs#L99
https://github.com/xamarin/LibZipSharp/blob/master/ZipArchive.cs#L103
https://github.com/xamarin/LibZipSharp/blob/master/ZipArchive.cs#L107
https://github.com/xamarin/LibZipSharp/blob/master/ZipArchive.cs#L111
https://github.com/xamarin/LibZipSharp/blob/master/ZipArchive.cs#L115
https://github.com/xamarin/LibZipSharp/blob/master/ZipArchive.cs#L119
https://github.com/xamarin/LibZipSharp/blob/master/ZipArchive.cs#L123
https://github.com/xamarin/LibZipSharp/blob/master/ZipArchive.cs#L127
https://github.com/xamarin/LibZipSharp/blob/master/ZipArchive.cs#L134
https://github.com/xamarin/LibZipSharp/blob/master/ZipArchive.cs#L200
https://github.com/xamarin/LibZipSharp/blob/master/ZipArchive.cs#L233
https://github.com/xamarin/LibZipSharp/blob/master/ZipArchive.cs#L237
https://github.com/xamarin/LibZipSharp/blob/master/ZipArchive.cs#L241
https://github.com/xamarin/LibZipSharp/blob/master/ZipArchive.cs#L245
https://github.com/xamarin/LibZipSharp/blob/master/ZipArchive.cs#L249
https://github.com/xamarin/LibZipSharp/blob/master/ZipArchive.cs#L253
https://github.com/xamarin/LibZipSharp/blob/master/ZipArchive.cs#L257
https://github.com/xamarin/LibZipSharp/blob/master/ZipArchive.cs#L261
https://github.com/xamarin/LibZipSharp/blob/master/ZipArchive.cs#L268
https://github.com/xamarin/LibZipSharp/blob/master/ZipArchive.cs#L395

### PR DESCRIPTION
**Pull request by dellis1972**
Fixed #72

### CODE REVIEW

**Review by brendanzagaeski — COMMENTED** [review]
_Quick first note and recap some discussion outside GitHub:_

It looks like the messages here are mostly exception messages. Since this is the first xamarin-android dependency to tackle exception messages, that raises some small questions about what kind of adjustments to make to the wording of the exception messages to help make them more easily localizable. Based on a first glance at the current wordings, I think maybe using full sentences where it's not too awkward might be worthwhile.

To give a tiny first example, maybe `must not be null or empty` can be adjusted just slightly to add the name of the argument at the beginning of the message. That will align it with some [similar messages in dotnet/sdk](https://github.com/dotnet/sdk/search?q=%22cannot+be+null+or+whitespace%22) and make it a full sentence:

```diff
 <data name="MustNotBeNullOrEmpty" xml:space="preserve">
-  <value>Must not be null or empty.</value>
-  <comment>Must not be null or empty.</comment>
+  <value>{0} must not be null or empty.</value>
+  <comment>{0} - The name of the parameter</comment>
 </data>
```

Though this is technically a little redundant since the exception also accepts the type name as a separate argument and surfaces it separately, the benefit is that the redundancy provides more context for the localization team.

File: UnixPlatformServices.cs [hunk 1]
```diff
@@ -63,7 +64,7 @@ public bool ReadAndProcessExtraFields (ZipEntry zipEntry)
 		{
 			var entry = zipEntry as UnixZipEntry;
 			if (entry == null)
-				throw new ArgumentException ("Invalid entry type, expected UnixZipEntry", nameof (zipEntry));
+				throw new ArgumentException (string.Format (Resources.InvalidEntryType, typeof(ZipEntry).Name), nameof (zipEntry));
```
[the remark this answers is not in the document]
Comment (dellis1972) [reply UnixPlatformServices.cs:67]: that's something @jonpryor would pick up on so don't feel bad :D the IDE failed me again 🤦

File: Properties/Resources.Designer.cs [hunk 2]
```diff
@@ -0,0 +1,224 @@
+﻿//------------------------------------------------------------------------------
```
Comment (brendanzagaeski) [inline Properties/Resources.Designer.cs:1]: A question about _Resources.Designer.cs_ that might be worth a quick discussion is which of the three following options is preferred for this initial LibZipSharp localization PR:

1. Use the output of the generator from Visual Studio for Mac? Advantages: The primary LibZipSharp maintainers work on macOS.
2. Use the output of the generator from Visual Studio on Windows? Advantages: The generators includes `global::` prefixes on `System` types and generates `/// <summary>` blocks on each of the generated properties.
3. Use an alternative generator that doesn't require Visual Studio at all? For example, I recently learned that the Xamarin UITools team uses an alternative that Jérémie adapted (https://github.com/garuma/ResxStrongifier) from another package kzu set up. (Example non-public commit a few other details: <https://github.com/xamarin/UITools/commit/cadbac0177887f4409beabdcb0ccb20dec45fa60>)

So far, xamarin-android, java.interop, and xamarin-android-tools have all gone with option 2. I was imagining that they could transition to option 3 in the future. Originally, I was picturing that xamarin-android could switch to [a generator that's part of dotnet/arcade](https://github.com/dotnet/arcade/blob/72b28b7e023d4c3fffa0a0b9748a7d4e8cc799be/src/Microsoft.DotNet.Arcade.Sdk/src/GenerateResxSource.cs). I haven't yet had a chance to experiment with the dotnet/arcade NuGet package to see if it would be unpleasant to try to use it just for that one generator task, but if it turns out to be easy, that might be an option for LibZipSharp too.

**Review by brendanzagaeski — COMMENTED** [review]
Thanks for all the work on this! Here are a few comments and questions about the localization build setup. I'll plan to do one more pass to look through the _.resx_ file and the message wordings tomorrow.

File: libZipSharp.csproj [hunk 3]
```diff
@@ -52,9 +57,24 @@
         <None Include="external\libzip\LICENSE" PackagePath="Licences\libzip" Pack="true" />
         <Compile Remove="ZipTest/**/*" />
         <Compile Remove="LibZipSharp.UnitTest/**/*" />
+        <None Include="@(_LocalizationLanguages-&gt;'Properties\xlf\Resources.%(Identity).xlf')" />
     </ItemGroup>
     <ItemGroup>
-      <PackageReference Include="Mono.Posix.NETStandard" Version="1.0.0" PrivateAssets="none" />
+      <PackageReference Include="Mono.Posix.NETStandard" Version="1.0.0" PrivateAssets="none" IncludeAssets="none" />
```
[the remark this answers is not in the document]
Comment (dellis1972) [reply libZipSharp.csproj:63]: I think it is needed for certain situations (like setting unix permissions) so I should fix that. While we don't want to compile against it, we still need a runtime dependency on the MonoPosixHelper.so/dylib

File: Properties/Resources.Designer.cs (hunk 2 above)
Comment (dellis1972) [reply Properties/Resources.Designer.cs:1]: to add to this, one of the maintainers works on linux the other on Mac. So I'm not sure what to do about this. 
I do feel however it can wait for later.

Comment (dellis1972) [reply Properties/Resources.Designer.cs:1]: Perhaps create an issue for this in x-a? We should standardise across all of our repo, since this will be a "thing" once we complete all the localisation.

Comment (brendanzagaeski) [reply Properties/Resources.Designer.cs:1]: Apologies for the delay on the next review step for this PR. I took a little detour to see if I could indeed set up the dotnet/arcade approach in xamarin-android. It's looking promising: <https://github.com/xamarin/xamarin-android/pull/5270>. If that PR goes through building and testing cleanly, I think the same approach could optionally be applied here too without much trouble (importing a couple files and setting a property).

In either case, I'll plan to get right back to reviewing this LibZipSharp PR tomorrow!

File: Properties/Resources.resx [hunk 4]
```diff
@@ -0,0 +1,247 @@
...
+    <value>Error occured while reading the Stream.</value>
+    <comment></comment>
+  </data>
+  <data name="StreamDoesNotSupportSeeking" xml:space="preserve">
+    <value>Stream does not support seeking.</value>
+    <comment></comment>
+  </data>
+  <data name="UnexpectedLibZipError_error" xml:space="preserve">
+    <value>Unexpected libzip error: {0}.</value>
+    <comment>{0} - An error message from libzip.</comment>
```
Comment (brendanzagaeski) [inline Properties/Resources.resx:213]: Maybe to add a comment for safety since `libzip` is lowercase:

```
<comment>The following is the name of a library and should not be translated: libzip
{0} - An error message from libzip.</comment>
```

File: Properties/Resources.resx [hunk 5]
```diff
@@ -0,0 +1,247 @@
...
+    <comment>{0} - A filename.</comment>
+  </data>
+  <data name="ErrorReadingFile_file" xml:space="preserve">
+    <value>Error occured while reading the file {0}.</value>
+    <comment>{0} - A filename.</comment>
+  </data>
+  <data name="FileDoesNotSupportSeeking_file" xml:space="preserve">
+    <value>The file {0} does not support seeking.</value>
+    <comment>{0} - A filename.</comment>
+  </data>
```
Comment (brendanzagaeski) [inline Properties/Resources.resx:238]: To add the new `''` convention and adjust `occured` to `occurred`:

```
  <data name="FileFailedConsistencyChecks_file" xml:space="preserve">
    <value>The file '{0}' failed consistency checks.</value>
    <comment>{0} - A filename.</comment>
  </data>
  <data name="FileDoesNotExist_file" xml:space="preserve">
    <value>The file '{0}' does not exist and file creation wasn't requested.</value>
    <comment>{0} - A filename.</comment>
  </data>
  <data name="FileIsNotAZip_file" xml:space="preserve">
    <value>The file '{0}' is not a ZIP archive.</value>
    <comment>{0} - A filename.</comment>
  </data>
  <data name="FileCouldNotBeOpened_file" xml:space="preserve">
    <value>The file '{0}' could not be opened.</value>
    <comment>{0} - A filename.</comment>
  </data>
  <data name="ErrorReadingFile_file" xml:space="preserve">
    <value>An error occurred while reading the file '{0}'.</value>
    <comment>{0} - A filename.</comment>
  </data>
  <data name="FileDoesNotSupportSeeking_file" xml:space="preserve">
    <value>The file '{0}' does not support seeking.</value>
    <comment>{0} - A filename.</comment>
  </data>
```

File: Properties/Resources.resx [hunk 6]
```diff
@@ -0,0 +1,247 @@
...
+  <data name="DestinationMustNotBeEmpty" xml:space="preserve">
+    <value>Archive destination path must not be empty.</value>
+    <comment></comment>
+  </data>
+  <data name="UnknownError" xml:space="preserve">
+    <value>Unknown Error.</value>
```
Comment (brendanzagaeski) [inline Properties/Resources.resx:244]: Maybe just to remove any ambiguity for the localization team about whether Error is capitalized for a special reason in this context:

```
<value>Unknown error</value>
```

File: UnixPlatformServices.cs [hunk 7]
```diff
@@ -338,7 +339,7 @@ bool SetEntryPermissions (ZipArchive archive, ulong index, EntryPermissions requ
 		{
 			var unixArchive = archive as UnixZipArchive;
 			if (unixArchive == null)
-				throw new InvalidOperationException ("Expected instance of UnixZipArchive");
+				throw new InvalidOperationException (string.Format (Resources.ExpectedAnInstanceOf_string_type, typeof (UnixZipArchive).Name, nameof(archive), archive.GetType ().Name));
```
Comment (brendanzagaeski) [inline UnixPlatformServices.cs:342]: Little missing space in `nameof (archive)`

File: UnixPlatformServices.cs [hunk 8]
```diff
@@ -382,9 +383,9 @@ public bool SetFileProperties (ZipEntry zipEntry, string extractedFilePath, bool
 		{
 			var entry = zipEntry as UnixZipEntry;
 			if (entry == null)
-				throw new ArgumentException ("Invalid entry type, expected UnixZipEntry", nameof (zipEntry));
+				throw new ArgumentException (string.Format (Resources.InvalidEntryType_string_type, nameof (zipEntry), typeof(UnixZipEntry).Name, zipEntry.GetType ().Name), nameof (zipEntry));
```
Comment (brendanzagaeski) [inline UnixPlatformServices.cs:386]: Little missing space in `typeof (UnixZipEntry).Name`

File: WindowsPlatformServices.cs [hunk 9]
```diff
@@ -61,7 +62,7 @@ public bool ReadAndProcessExtraFields (ZipEntry zipEntry)
 		{
 			var entry = zipEntry as WindowsZipEntry;
 			if (entry == null)
-				throw new ArgumentException ("Invalid entry type, expected WindowsZipEntry", nameof (zipEntry));
+				throw new ArgumentException (string.Format (Resources.InvalidEntryType_string_type, nameof (zipEntry), typeof(WindowsZipEntry).Name, zipEntry.GetType ().Name), nameof (zipEntry));
```
Comment (brendanzagaeski) [inline WindowsPlatformServices.cs:65]: Little missing space in `typeof (WindowsZipEntry).Name`

File: WindowsPlatformServices.cs [hunk 10]
```diff
@@ -210,7 +211,7 @@ bool SetEntryPermissions (ZipArchive archive, ulong index, EntryPermissions requ
 		{
 			var windowsArchive = archive as WindowsZipArchive;
 			if (windowsArchive == null)
-				throw new InvalidOperationException ("Expected instance of WindowsZipArchive");
+				throw new InvalidOperationException (string.Format (Resources.ExpectedAnInstanceOf_string_type, typeof (WindowsZipArchive).Name, nameof(archive), archive.GetType ().Name));
```
Comment (brendanzagaeski) [inline WindowsPlatformServices.cs:214]: Little missing space in `nameof (archive)`

File: WindowsZipArchive.cs [hunk 11]
```diff
@@ -34,7 +35,7 @@ public class WindowsZipArchive : ZipArchive
 			get {
 				var opts = Options as WindowsPlatformOptions;
 				if (opts == null)
-					throw new InvalidOperationException ("Unexpected options type");
+					throw new InvalidOperationException (string.Format (Resources.UnexpectedOptionsType_string_type_type, nameof(Options), typeof (WindowsPlatformOptions).Name, Options?.GetType ()?.Name ?? "Unknown"));
```
Comment (brendanzagaeski) [inline WindowsZipArchive.cs:38]: Little missing space in `nameof (Options)`

File: Properties/Resources.resx [hunk 12]
```diff
@@ -0,0 +1,247 @@
...
+  </data>
+  <data name="UnexpectedOptionsType_string_type_type" xml:space="preserve">
+    <value>Unexpected options type for {0}. Expected {1} but got {2}.</value>
+    <comment>{0} - The parameter name.
+{1} - The expected type of the parameter.
+{2} - The actual type of the parameter.</comment>
+  </data>
+  <data name="FileAlreadyExists" xml:space="preserve">
+    <value>The file already exists.</value>
+    <comment></comment>
```
Comment (brendanzagaeski) [inline Properties/Resources.resx:177]: There's a little gotcha with the XliffTasks tooling that it doesn't like empty `<comment></comment>` elements (<https://github.com/dotnet/xliff-tasks/issues/342>), so all of the empty elements can be removed to make XliffTasks happy.

**Review by brendanzagaeski — COMMENTED** [review]
Nice work on the new message wordings! Here are ideas for a few little adjustments. One other little bit of tidy up that might be a nice finishing touch could be to alphabetize the entries by `name` in the `.resx` file.

File: libZipSharp.csproj (hunk 3 above)
[the remark this answers is not in the document]
Comment (brendanzagaeski) [reply libZipSharp.csproj]: The new approach in the latest commit on the PR brings back the behavior where downstream consumers of LibZipSharp also install the Mono.Posix.NETStandard NuGet package and get the _MonoPosixHelper_ platform-specific native library. I'll accordingly mark this conversation as resolved.

**Review by grendello — APPROVED** [review]
